apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: heartbeat
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
